import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Alert, Button, Card, Collapse, Descriptions, message, Space, Spin, Table, Typography } from "antd";

import { getTradingNarrative } from "../../api/engineClient";
import { useI18n } from "../../app/i18n";
import type { TradingNarrativeFilters } from "../../types/narrative";
import { InsightFilters } from "./InsightFilters";

export function AiPromptPage() {
  const { t } = useI18n(); const [filters, setFilters] = useState<TradingNarrativeFilters>(); const [messages, contextHolder] = message.useMessage(); const narrative = useMutation({ mutationFn: getTradingNarrative }); const generate = (value: TradingNarrativeFilters) => { setFilters(value); narrative.mutate(value); };
  const copy = async () => { try { await navigator.clipboard.writeText(narrative.data?.narrative ?? ""); messages.success(t("narrative.copied")); } catch { messages.error(t("narrative.copyFailed")); } };
  return <div>{contextHolder}<Card title={t("narrative.title")} style={{ marginBottom: 16 }}><Typography.Paragraph type="secondary">{t("narrative.description")}</Typography.Paragraph><InsightFilters onChange={generate} /></Card>{narrative.isPending && <Spin />}{narrative.isError && <Alert type="error" message={narrative.error.message} showIcon />}{narrative.data && <Space direction="vertical" size="large" style={{ width: "100%" }}><Card extra={<Button onClick={() => void copy()}>{t("narrative.copy")}</Button>}><Descriptions size="small" bordered column={3} style={{ marginBottom: 16 }}><Descriptions.Item label={t("narrative.tradeCount")}>{narrative.data.trade_count}</Descriptions.Item><Descriptions.Item label={t("narrative.marketCount")}>{narrative.data.markets.length}</Descriptions.Item><Descriptions.Item label={t("narrative.range")}>{filters ? `${new Date(filters.from_time).toLocaleDateString()} ${t("narrative.start")} ${new Date(filters.to_time).toLocaleDateString()}` : ""}</Descriptions.Item></Descriptions><pre style={{ whiteSpace: "pre-wrap", background: "#f8fafc", padding: 20, overflow: "auto", margin: 0 }}>{narrative.data.narrative}</pre></Card>{narrative.data.diagnostics.length > 0 && <Alert type="warning" showIcon message={t("narrative.coverage")} description={narrative.data.diagnostics.join("；")} />}<Collapse items={narrative.data.markets.map((market) => ({ key: market.symbol, label: `${market.symbol} · ${market.timeframe} · ${t("narrative.candles", { count: market.candle_count })}`, children: <Table size="small" pagination={false} rowKey={(_, index) => String(index)} dataSource={market.phases} columns={[{ title: t("narrative.phase"), dataIndex: "trend" }, { title: t("narrative.start"), dataIndex: "from_time" }, { title: t("narrative.end"), dataIndex: "to_time" }, { title: t("narrative.change"), dataIndex: "change_percent", render: (value) => `${value}%` }]} /> }))} /><Collapse items={[{ key: "timeline", label: t("narrative.timeline", { count: narrative.data.timeline.length }), children: <Table size="small" pagination={{ pageSize: 20 }} rowKey={(item) => `${item.type}-${item.trade_id}`} dataSource={narrative.data.timeline} columns={[{ title: t("narrative.time"), dataIndex: "time" }, { title: t("trades.symbol"), dataIndex: "symbol" }, { title: t("trades.direction"), dataIndex: "direction" }, { title: t("narrative.action"), dataIndex: "action" }, { title: t("narrative.price"), dataIndex: "price" }, { title: t("trades.netProfit"), dataIndex: "net_profit", render: (value) => value ?? t("common.none") }]} /> }]} /></Space>}</div>;
}
