import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import enUS from "antd/locale/en_US";
import zhCN from "antd/locale/zh_CN";

export type Language = "zh-CN" | "en-US";
type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  "zh-CN": {
    "nav.dashboard": "概览", "nav.datasource": "数据源", "nav.narrative": "交易过程叙事", "nav.trades": "交易记录", "nav.replay": "交易复盘", "nav.import": "CSV 兼容导入", "nav.export": "导出 TMF", "language.zh": "中文", "language.en": "English",
    "dashboard.connecting": "正在连接本地分析引擎", "dashboard.unavailable": "分析引擎未就绪", "dashboard.reconnect": "重新连接", "dashboard.connected": "本地分析引擎已连接", "dashboard.description": "默认从 MT5 同步已平仓交易；CSV 仅作为 MT5 不可用、历史迁移或其他平台数据的兼容导入。交易、复盘、画像和 TMF 文件始终在本机处理。", "dashboard.overview": "交易概览", "dashboard.tradeCount": "交易数", "dashboard.netProfit": "净盈亏", "dashboard.winRate": "胜率", "dashboard.profitFactor": "利润因子", "dashboard.lossStreak": "最长连亏", "dashboard.completedReviews": "已完成复盘", "dashboard.engineStatus": "引擎状态", "dashboard.runningStatus": "运行状态", "dashboard.engineVersion": "引擎版本", "dashboard.databaseStatus": "SQLite 状态",
    "chart.equity": "累计净盈亏", "chart.distribution": "品种分布", "chart.noTrades": "暂无交易数据", "chart.netProfit": "净盈亏",
    "datasource.unavailable": "无法读取数据源状态", "datasource.primary": "MT5 是默认交易数据源", "datasource.primaryDescription": "同步已平仓交易后，可直接进入交易记录、复盘、AI Prompt 和 TMF 导出。CSV 保留为 MT5 不可用或其他平台数据的兼容导入方式。", "datasource.recentSync": "最近 MT5 同步", "datasource.completedAt": "完成时间", "datasource.inProgress": "进行中", "datasource.status": "状态", "datasource.success": "成功", "datasource.failed": "失败", "datasource.symbol": "品种", "datasource.allSymbols": "全部品种", "datasource.writtenTrades": "写入交易", "datasource.diagnostic": "诊断", "datasource.csvImport": "CSV 兼容导入", "datasource.mt5Unavailable": "MT5 当前不可用", "datasource.connectOrImport": "请连接 MT5，或使用导航中的“导入交易”导入 CSV。",
    "mt5.title": "MetaTrader 5 连接", "mt5.reconnect": "重新连接", "mt5.connect": "连接 MT5", "mt5.connected": "已连接", "mt5.disconnected": "未连接", "mt5.terminalVersion": "终端版本", "mt5.terminalPath": "终端路径", "mt5.unknown": "未知", "mt5.accountInfo": "账户信息", "mt5.hideAccount": "隐藏敏感账户信息", "mt5.showAccount": "显示敏感账户信息", "mt5.account": "账户", "mt5.server": "服务器", "mt5.balance": "余额", "mt5.equity": "净值",
    "sync.title": "同步 MT5 已平仓交易", "sync.symbol": "交易品种（可选）", "sync.allSymbols": "全部品种", "sync.closeRange": "平仓时间范围", "sync.allHistory": "同步全部交易历史", "sync.submit": "同步交易历史", "sync.complete": "MT5 历史同步完成", "sync.summary": "新增 {imported} 笔，更新 {updated} 笔，跳过 {skipped} 笔。",
    "trades.title": "交易记录", "trades.source": "来源", "trades.direction": "方向", "trades.batchReview": "批量生成复盘（{count}）", "trades.batchDelete": "批量删除（{count}）", "trades.confirmSelected": "删除选中的 {count} 笔交易？", "trades.confirmOne": "删除这笔交易？", "trades.deleteNotice": "将同时删除所选交易的复盘上下文。若再次同步 MT5 历史，相同成交可能被重新导入。", "common.delete": "删除", "common.cancel": "取消", "common.allSymbols": "全部品种", "trades.ticket": "订单", "trades.symbol": "品种", "trades.open": "开仓", "trades.close": "平仓", "trades.volume": "手数", "trades.netProfit": "净盈亏", "trades.actions": "操作", "trades.review": "复盘", "trades.reviewAll": "复盘全部", "trades.deleteAll": "删除全部", "trades.confirmDeleteAllTitle": "删除所有已存储交易？", "trades.confirmDeleteAllDescription": "此操作忽略当前筛选，将删除全部 MT5 和 CSV 交易及其复盘上下文，无法撤销。MT5 交易可再次同步，CSV 交易需重新导入。", "trades.continueDelete": "继续", "trades.confirmDeleteAllFinalTitle": "最终确认：删除全部交易", "trades.confirmDeleteAllTypePrompt": "请输入 DELETE 以确认永久删除所有已存储交易。",
    "review.batchTitle": "批量复盘结果", "review.processed": "已处理 {count} 笔交易", "review.completed": "完成 {count}", "review.insufficient": "数据不足 {count}", "review.failed": "失败 {count}", "review.trade": "交易 #{id}：", "review.noDiagnostic": "未提供诊断信息。", "review.drawer": "{symbol} · {ticket} 复盘", "review.generate": "生成复盘", "review.reanalyze": "重新分析", "review.completedStatus": "分析完成", "review.notAnalyzed": "尚未生成复盘。分析会自动从 MT5 补齐所需历史K线。", "review.insufficientData": "可用K线不足。", "review.replay": "行情回放", "review.market": "入场市场环境", "review.execution": "执行与风险", "review.dataQuality": "数据质量", "review.trend": "趋势", "review.rsi": "RSI(14)", "review.atr": "ATR(14)", "review.ema": "EMA20 / EMA50", "review.support": "支撑", "review.resistance": "阻力", "review.mfe": "MFE（价格）", "review.mae": "MAE（价格）", "review.drawdown": "最大回撤（价格）", "review.realNetProfit": "真实净盈亏", "review.requiredPre": "所需入场前K线", "review.availablePre": "可用入场前K线", "review.holding": "持仓期间K线", "review.post": "平仓后K线", "review.fetched": "从 MT5 获取的K线", "review.note": "说明", "review.replayHelp": "图表时间为 UTC+0。BUY：开多向上、平多向下；SELL：开空向下、平空向上。开仓与平仓以连线表示，止损和止盈保留为水平线；图表自动适配全部K线。",
    "market.stopLoss": "止损", "market.takeProfit": "止盈", "market.lots": "手", "market.openBuy": "开多", "market.openSell": "开空", "market.closeBuy": "平多", "market.closeSell": "平空", "market.noCandles": "没有可用于复盘的历史K线",
    "replay.title": "交易复盘", "replay.noTrades": "暂无可播放的交易记录", "replay.symbol": "交易品种", "replay.selectSymbol": "请选择一个品种", "replay.range": "回放时间范围", "replay.timeframe": "K线周期", "replay.displayTimezone": "图表时区", "replay.timezoneLocal": "本机时区", "replay.auto": "自动", "replay.preRoll": "前置K线", "replay.postRoll": "后置K线", "replay.rangeProfit": "范围内净收益", "replay.realizedProfit": "已实现净收益", "replay.tradeCount": "{count} 笔交易", "replay.closedCount": "已平仓 {closed} / {total} 笔", "replay.preRollShown": "前置K线：{actual} / {requested}", "replay.available": "可选范围：{from} 至 {to}", "replay.load": "加载回放", "replay.expanded": "实际播放行情：{from} 至 {to}", "replay.play": "播放", "replay.pause": "暂停", "replay.back": "后退一根", "replay.forward": "前进一根", "replay.progress": "播放进度", "replay.close": "平仓", "replay.tradeId": "交易 ID", "replay.profit": "原始盈亏", "replay.costs": "手续费 / 隔夜费", "replay.holding": "持仓时长", "replay.closeReason": "平仓原因", "replay.seek": "回放进度", "replay.seekStart": "前置行情末尾", "replay.seekEnd": "回放结束", "replay.export": "导出当前复盘", "replay.exportTitle": "导出当前复盘 TMF", "replay.exportDescription": "将在本机生成包含当前回放 K 线、实际周期、播放进度和全部生命周期重叠交易的 TMF 文件。不会下单、修改订单或上传数据。", "replay.exportCursor": "当前播放位置", "replay.exportLifecycle": "导出所有与所选范围生命周期重叠的交易。", "replay.exportGenerate": "生成并选择位置保存", "replay.exportUnavailable": "当前回放没有可导出的 K 线。",
    "indicator.open": "技术指标", "indicator.settings": "技术指标设置", "indicator.done": "完成", "indicator.add": "添加", "indicator.addSma": "添加 SMA", "indicator.addEma": "添加 EMA", "indicator.restoreDefaults": "恢复默认", "indicator.remove": "删除", "indicator.empty": "尚未添加指标。", "indicator.parameter.period": "周期", "indicator.parameter.std_dev": "标准差", "indicator.parameter.fast": "快线", "indicator.parameter.slow": "慢线", "indicator.parameter.signal": "信号", "indicator.legendToggle": "切换 {name} 显示",
    "narrative.title": "交易过程叙事", "narrative.description": "将所选范围内的订单与同一时期 K 线按时间线组合，生成可直接交给 AI 分析的客观中文描述。", "narrative.copied": "已复制交易过程叙事", "narrative.copyFailed": "无法复制到剪贴板，请检查系统权限。", "narrative.copy": "复制叙事", "narrative.tradeCount": "交易数量", "narrative.marketCount": "品种数量", "narrative.range": "筛选范围", "narrative.coverage": "数据覆盖限制", "narrative.candles": "{count} 根K线", "narrative.phase": "阶段", "narrative.start": "开始", "narrative.end": "结束", "narrative.change": "涨跌幅", "narrative.timeline": "结构化交易时间线（{count} 个动作）", "narrative.time": "时间", "narrative.action": "动作", "narrative.price": "价格", "common.none": "—", "filters.symbol": "品种，例如 EURUSD", "filters.selectRange": "请选择交易范围", "filters.availableRange": "可选范围：{from} 至 {to}", "filters.noTrades": "暂无交易记录，无法选择日期", "filters.generate": "生成交易过程叙事", "filters.rangeError": "无法读取交易日期范围",
    "import.title": "CSV 兼容导入", "import.description": "仅在 MT5 不可用、迁移历史记录或导入其他平台数据时使用 CSV。", "import.select": "选择 CSV", "import.map": "确认字段", "import.complete": "完成导入", "import.chooseFile": "选择经纪商 CSV 文件", "import.file": "文件", "import.encoding": "编码", "import.delimiter": "分隔符", "import.mapping": "字段映射", "import.confirm": "确认并导入", "import.result": "导入完成：新增 {imported} 笔，重复跳过 {duplicates} 笔，错误 {errors} 行。", "field.ticket": "订单号", "field.symbol": "交易品种", "field.direction": "方向", "field.open_time": "开仓时间", "field.close_time": "平仓时间", "field.open_price": "开仓价", "field.close_price": "平仓价", "field.volume": "交易量", "field.profit": "盈亏", "field.commission": "手续费", "field.swap": "隔夜费", "field.stop_loss": "止损", "field.take_profit": "止盈", "field.close_reason": "平仓原因",
    "export.title": "导出 TMF", "export.info": "TMF 是可解压的本地 ZIP 文件，可以直接上传给AI进行分析。它包含交易过程叙事、结构化时间线、历史交易、上下文、统计与可选 PNG 图表。", "export.symbol": "品种", "export.example": "例如 EURUSD", "export.closeRange": "平仓日期范围", "export.charts": "导出交易图表", "export.chartsHint": "需在“交易记录”中点击“复盘”生成交易图表。", "export.includeCharts": "包含 PNG", "export.excludeCharts": "不含图表", "export.redact": "脱敏订单与来源", "export.redacted": "已脱敏", "export.notRedacted": "不脱敏", "export.redactHelp": "移除订单号、导入批次及来源标识；价格、行情、品种与时间保持不变。", "export.generate": "生成并保存 TMF", "export.success": "TMF 已生成并校验", "export.successDetail": "共 {count} 笔交易，{charts}。", "export.withCharts": "已包含图表", "export.withoutCharts": "未包含图表", "export.save": "选择位置保存 .tmf"
  },
  "en-US": {
    "nav.dashboard": "Overview", "nav.datasource": "Data Sources", "nav.narrative": "Trading Narrative", "nav.trades": "Trades", "nav.replay": "Trade Replay", "nav.import": "CSV Import", "nav.export": "Export TMF", "language.zh": "中文", "language.en": "English",
    "dashboard.connecting": "Connecting to local analysis engine", "dashboard.unavailable": "Analysis engine is unavailable", "dashboard.reconnect": "Reconnect", "dashboard.connected": "Local analysis engine connected", "dashboard.description": "Closed trades are synchronized from MT5 by default. CSV remains a compatibility import for unavailable MT5, migrated history, or other platforms. Trades, reviews, profiles, and TMF files are always processed locally.", "dashboard.overview": "Trading Overview", "dashboard.tradeCount": "Trades", "dashboard.netProfit": "Net Profit", "dashboard.winRate": "Win Rate", "dashboard.profitFactor": "Profit Factor", "dashboard.lossStreak": "Longest Losing Streak", "dashboard.completedReviews": "Completed Reviews", "dashboard.engineStatus": "Engine Status", "dashboard.runningStatus": "Status", "dashboard.engineVersion": "Engine Version", "dashboard.databaseStatus": "SQLite Status",
    "chart.equity": "Cumulative Net Profit", "chart.distribution": "Symbol Distribution", "chart.noTrades": "No trade data", "chart.netProfit": "Net Profit",
    "datasource.unavailable": "Unable to read data source status", "datasource.primary": "MT5 is the default trade data source", "datasource.primaryDescription": "After synchronizing closed trades, you can use Trades, Reviews, AI Prompt, and TMF export directly. CSV remains a compatibility import for unavailable MT5 or other platforms.", "datasource.recentSync": "Latest MT5 Sync", "datasource.completedAt": "Completed At", "datasource.inProgress": "In progress", "datasource.status": "Status", "datasource.success": "Success", "datasource.failed": "Failed", "datasource.symbol": "Symbol", "datasource.allSymbols": "All symbols", "datasource.writtenTrades": "Written Trades", "datasource.diagnostic": "Diagnostic", "datasource.csvImport": "CSV Compatibility Import", "datasource.mt5Unavailable": "MT5 is unavailable", "datasource.connectOrImport": "Connect MT5 or import a CSV from the navigation.",
    "mt5.title": "MetaTrader 5 Connection", "mt5.reconnect": "Reconnect", "mt5.connect": "Connect MT5", "mt5.connected": "Connected", "mt5.disconnected": "Disconnected", "mt5.terminalVersion": "Terminal Version", "mt5.terminalPath": "Terminal Path", "mt5.unknown": "Unknown", "mt5.accountInfo": "Account Information", "mt5.hideAccount": "Hide sensitive account information", "mt5.showAccount": "Show sensitive account information", "mt5.account": "Account", "mt5.server": "Server", "mt5.balance": "Balance", "mt5.equity": "Equity",
    "sync.title": "Synchronize Closed MT5 Trades", "sync.symbol": "Symbol (optional)", "sync.allSymbols": "All symbols", "sync.closeRange": "Close Time Range", "sync.allHistory": "Synchronize all trade history", "sync.submit": "Synchronize Trade History", "sync.complete": "MT5 history synchronized", "sync.summary": "Added {imported}, updated {updated}, skipped {skipped}.",
    "trades.title": "Trades", "trades.source": "Source", "trades.direction": "Direction", "trades.batchReview": "Generate Reviews ({count})", "trades.batchDelete": "Delete Selected ({count})", "trades.confirmSelected": "Delete {count} selected trades?", "trades.confirmOne": "Delete this trade?", "trades.deleteNotice": "The review context for the selected trades will also be deleted. The same deals may be re-imported in a later MT5 history synchronization.", "common.delete": "Delete", "common.cancel": "Cancel", "common.allSymbols": "All symbols", "trades.ticket": "Ticket", "trades.symbol": "Symbol", "trades.open": "Open", "trades.close": "Close", "trades.volume": "Volume", "trades.netProfit": "Net Profit", "trades.actions": "Actions", "trades.review": "Review", "trades.reviewAll": "Review All", "trades.deleteAll": "Delete All", "trades.confirmDeleteAllTitle": "Delete all stored trades?", "trades.confirmDeleteAllDescription": "This ignores the current filters and permanently deletes all MT5 and CSV trades with their review contexts. MT5 trades can be synchronized again; CSV trades must be imported again.", "trades.continueDelete": "Continue", "trades.confirmDeleteAllFinalTitle": "Final confirmation: delete all trades", "trades.confirmDeleteAllTypePrompt": "Type DELETE to permanently remove all stored trades.",
    "review.batchTitle": "Batch Review Results", "review.processed": "Processed {count} trades", "review.completed": "Completed {count}", "review.insufficient": "Insufficient data {count}", "review.failed": "Failed {count}", "review.trade": "Trade #{id}: ", "review.noDiagnostic": "No diagnostic information provided.", "review.drawer": "{symbol} · {ticket} Review", "review.generate": "Generate Review", "review.reanalyze": "Analyze Again", "review.completedStatus": "Analysis Complete", "review.notAnalyzed": "No review has been generated. Analysis automatically retrieves the required historical MT5 candles.", "review.insufficientData": "Not enough candles are available.", "review.replay": "Market Replay", "review.market": "Market Context at Entry", "review.execution": "Execution and Risk", "review.dataQuality": "Data Quality", "review.trend": "Trend", "review.rsi": "RSI (14)", "review.atr": "ATR (14)", "review.ema": "EMA20 / EMA50", "review.support": "Support", "review.resistance": "Resistance", "review.mfe": "MFE (price)", "review.mae": "MAE (price)", "review.drawdown": "Maximum Drawdown (price)", "review.realNetProfit": "Actual Net Profit", "review.requiredPre": "Required pre-entry candles", "review.availablePre": "Available pre-entry candles", "review.holding": "Holding-period candles", "review.post": "Post-close candles", "review.fetched": "Candles fetched from MT5", "review.note": "Note", "review.replayHelp": "Chart times are UTC+0. BUY: entry arrow up, exit arrow down; SELL: entry arrow down, exit arrow up. Entry and exit are connected; stop loss and take profit remain horizontal lines; the chart fits all candles automatically.",
    "market.stopLoss": "Stop Loss", "market.takeProfit": "Take Profit", "market.lots": "lots", "market.openBuy": "Buy Entry", "market.openSell": "Sell Entry", "market.closeBuy": "Buy Exit", "market.closeSell": "Sell Exit", "market.noCandles": "No historical candles are available for review",
    "replay.title": "Trading Replay Player", "replay.noTrades": "No trades are available for replay", "replay.symbol": "Symbol", "replay.selectSymbol": "Select one symbol", "replay.range": "Replay range", "replay.timeframe": "Timeframe", "replay.displayTimezone": "Chart timezone", "replay.timezoneLocal": "Local system time", "replay.auto": "Auto", "replay.preRoll": "Pre-roll candles", "replay.postRoll": "Post-roll candles", "replay.rangeProfit": "Range net profit", "replay.realizedProfit": "Realized net profit", "replay.tradeCount": "{count} trades", "replay.closedCount": "Closed {closed} / {total}", "replay.preRollShown": "Pre-roll: {actual} / {requested}", "replay.available": "Available range: {from} to {to}", "replay.load": "Load replay", "replay.expanded": "Played market window: {from} to {to}", "replay.play": "Play", "replay.pause": "Pause", "replay.back": "Step back", "replay.forward": "Step forward", "replay.progress": "Progress", "replay.close": "Close", "replay.tradeId": "Trade ID", "replay.profit": "Gross profit", "replay.costs": "Commission / Swap", "replay.holding": "Holding duration", "replay.closeReason": "Close reason", "replay.seek": "Replay progress", "replay.seekStart": "Pre-roll end", "replay.seekEnd": "Replay end", "replay.export": "Export Current Replay", "replay.exportTitle": "Export Current Replay TMF", "replay.exportDescription": "Generates a local TMF with the current replay candles, resolved timeframe, playback position, and all lifecycle-overlapping trades. It never places, changes, or uploads trades.", "replay.exportCursor": "Current playback position", "replay.exportLifecycle": "Exports every trade whose lifecycle overlaps the selected range.", "replay.exportGenerate": "Generate and Choose Save Location", "replay.exportUnavailable": "The current replay has no candles to export.",
    "indicator.open": "Indicators", "indicator.settings": "Indicator Settings", "indicator.done": "Done", "indicator.add": "Add", "indicator.addSma": "Add SMA", "indicator.addEma": "Add EMA", "indicator.restoreDefaults": "Restore Defaults", "indicator.remove": "Remove", "indicator.empty": "No indicators have been added.", "indicator.parameter.period": "Period", "indicator.parameter.std_dev": "Std Dev", "indicator.parameter.fast": "Fast", "indicator.parameter.slow": "Slow", "indicator.parameter.signal": "Signal", "indicator.legendToggle": "Toggle {name} visibility",
    "narrative.title": "Trading Narrative", "narrative.description": "Combines trades in the selected range with candles from the same period into an objective, chronological description ready for AI analysis.", "narrative.copied": "Trading narrative copied", "narrative.copyFailed": "Unable to copy to the clipboard. Check system permissions.", "narrative.copy": "Copy Narrative", "narrative.tradeCount": "Trades", "narrative.marketCount": "Symbols", "narrative.range": "Selected Range", "narrative.coverage": "Data Coverage Limits", "narrative.candles": "{count} candles", "narrative.phase": "Phase", "narrative.start": "Start", "narrative.end": "End", "narrative.change": "Change", "narrative.timeline": "Structured Trade Timeline ({count} actions)", "narrative.time": "Time", "narrative.action": "Action", "narrative.price": "Price", "common.none": "—", "filters.symbol": "Symbol, e.g. EURUSD", "filters.selectRange": "Select a trade range", "filters.availableRange": "Available range: {from} to {to}", "filters.noTrades": "No trades are available to select a date", "filters.generate": "Generate Trading Narrative", "filters.rangeError": "Unable to read the trade date range",
    "import.title": "CSV Compatibility Import", "import.description": "Use CSV only when MT5 is unavailable, for history migration, or to import data from another platform.", "import.select": "Select CSV", "import.map": "Confirm Fields", "import.complete": "Import Complete", "import.chooseFile": "Choose Broker CSV File", "import.file": "File", "import.encoding": "Encoding", "import.delimiter": "Delimiter", "import.mapping": "Field Mapping", "import.confirm": "Confirm and Import", "import.result": "Import complete: added {imported}, duplicate skipped {duplicates}, errors {errors} rows.", "field.ticket": "Ticket", "field.symbol": "Symbol", "field.direction": "Direction", "field.open_time": "Open Time", "field.close_time": "Close Time", "field.open_price": "Open Price", "field.close_price": "Close Price", "field.volume": "Volume", "field.profit": "Profit", "field.commission": "Commission", "field.swap": "Swap", "field.stop_loss": "Stop Loss", "field.take_profit": "Take Profit", "field.close_reason": "Close Reason",
    "export.title": "Export TMF", "export.info": "TMF is a local ZIP file that can be uploaded directly for AI analysis. It includes a trading narrative, structured timeline, historical trades, context, statistics, and optional PNG charts.", "export.symbol": "Symbol", "export.example": "e.g. EURUSD", "export.closeRange": "Close Date Range", "export.charts": "Export Trade Charts", "export.chartsHint": "Generate trade charts first by selecting Review in Trades.", "export.includeCharts": "Include PNG", "export.excludeCharts": "No Charts", "export.redact": "Redact Orders and Source", "export.redacted": "Redacted", "export.notRedacted": "Not Redacted", "export.redactHelp": "Removes ticket numbers, import batches, and source identifiers. Prices, market data, symbols, and times remain unchanged.", "export.generate": "Generate and Save TMF", "export.success": "TMF Generated and Validated", "export.successDetail": "{count} trades, {charts}.", "export.withCharts": "charts included", "export.withoutCharts": "charts not included", "export.save": "Choose Location to Save .tmf"
  },
};

interface I18nValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
  antdLocale: typeof zhCN;
}

const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem("trademirror-language") === "en-US" ? "en-US" : "zh-CN");
  useEffect(() => { localStorage.setItem("trademirror-language", language); }, [language]);
  const value = useMemo<I18nValue>(() => ({
    language,
    setLanguage,
    t: (key, values) => Object.entries(values ?? {}).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), dictionaries[language][key] ?? key),
    antdLocale: language === "zh-CN" ? zhCN : enUS,
  }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error("useI18n must be used within I18nProvider");
  return value;
}
