import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { invoke } from "@tauri-apps/api/core";
import { Alert, Button, Card, DatePicker, Form, Input, Result, Select, Space, Switch } from "antd";

import { createTmfExport } from "../../api/engineClient";
import { useI18n } from "../../app/i18n";
import type { TmfExportResponse } from "../../types/export";
import { useTradeDateRange } from "../trades/useTradeDateRange";

export function TmfExportPage() {
  const { t } = useI18n(); const [form] = Form.useForm(); const [result, setResult] = useState<TmfExportResponse | null>(null); const dateRange = useTradeDateRange(); const exportTmf = useMutation({ mutationFn: createTmfExport, onSuccess: setResult });
  const submit = (values: { symbol?: string; direction?: "BUY" | "SELL"; source?: "MT5" | "CSV"; range?: [{ startOf: (unit: string) => { toISOString: () => string } }, { endOf: (unit: string) => { toISOString: () => string } }]; include_charts: boolean; redact_source_identity: boolean }) => exportTmf.mutate({ symbol: values.symbol || undefined, direction: values.direction, source: values.source, from_time: values.range?.[0]?.startOf("day").toISOString(), to_time: values.range?.[1]?.endOf("day").toISOString(), include_charts: values.include_charts, redact_source_identity: values.redact_source_identity });
  const rangeHint = dateRange.hasTrades ? t("filters.availableRange", { from: dateRange.from?.format("YYYY-MM-DD") ?? "", to: dateRange.to?.format("YYYY-MM-DD") ?? "" }) : t("filters.noTrades");
  return <Card title={t("export.title")}><Alert type="info" showIcon style={{ marginBottom: 20 }} message={t("export.info")} /><Form form={form} layout="vertical" initialValues={{ include_charts: true, redact_source_identity: true }} onFinish={submit}><Space wrap align="start"><Form.Item label={t("export.symbol")} name="symbol"><Input placeholder={t("export.example")} /></Form.Item><Form.Item label={t("trades.source")} name="source"><Select allowClear placeholder={t("trades.source")} style={{ width: 130 }} options={[{ value: "MT5", label: "MT5" }, { value: "CSV", label: "CSV" }]} /></Form.Item><Form.Item label={t("trades.direction")} name="direction"><Select allowClear style={{ width: 130 }} options={[{ value: "BUY", label: "BUY" }, { value: "SELL", label: "SELL" }]} /></Form.Item><Form.Item label={t("export.closeRange")} name="range" extra={rangeHint}><DatePicker.RangePicker disabled={dateRange.isPending || !dateRange.hasTrades} disabledDate={(date) => !dateRange.hasTrades || date.isBefore(dateRange.from, "day") || date.isAfter(dateRange.to, "day")} /></Form.Item></Space><Form.Item label={t("export.charts")} name="include_charts" valuePropName="checked"><Switch checkedChildren={t("export.includeCharts")} unCheckedChildren={t("export.excludeCharts")} /></Form.Item><Form.Item label={t("export.redact")} name="redact_source_identity" valuePropName="checked" extra={t("export.redactHelp")}><Switch checkedChildren={t("export.redacted")} unCheckedChildren={t("export.notRedacted")} /></Form.Item><Button type="primary" htmlType="submit" loading={exportTmf.isPending}>{t("export.generate")}</Button></Form>{exportTmf.error && <Alert style={{ marginTop: 16 }} type="error" message={(exportTmf.error as Error).message} />}{result && <Result status="success" title={t("export.success")} subTitle={t("export.successDetail", { count: result.trade_count, charts: result.include_charts ? t("export.withCharts") : t("export.withoutCharts") })} extra={<Button type="primary" onClick={() => invoke("save_tmf_export", { exportId: result.export_id })}>{t("export.save")}</Button>} />}</Card>;
}
